name: Build crDroid for b4q

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install -y git wget curl python3 bc bison build-essential gcc g++ \
          zip unzip repo libncurses5 libssl-dev flex liblz4-tool \
          openjdk-11-jdk

    - name: Initialize Repo
      run: |
        mkdir crdroid && cd crdroid
        repo init -u https://github.com/crdroidandroid/android.git -b 15.0 --git-lfs
        repo sync -c --no-tags --no-clone-bundle --optimized-fetch --prune

    - name: Build ROM
      run: |
        cd crdroid
        . build/envsetup.sh
        lunch crdroid_b4q-userdebug
        mka bacon

    - name: Check output
      run: |
        ls -l out/target/product/b4q/*.zip || echo "No zip file found"

    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: crdroid_b4q_output
        path: out/target/product/b4q/*.zip
